-- 코드를 입력하세요
SELECT CATEGORY, SUM(BS.SALES) as TOTAL_SALES
FROM BOOK B inner join BOOK_SALES BS on B.BOOK_ID = BS.BOOK_ID
WHERE BS.SALES_DATE >= '2022-01-01' AND BS.SALES_DATE <= '2022-01-31'
GROUP BY CATEGORY
ORDER BY CATEGORY;